### PR TITLE
Form components: Added Select list and switchers

### PR DESCRIPTION
**Pull request by inakijv**
Most important aspects:
- Added Select list form component;
- Added Switchers (radio buttons and checkboxes styled) for On/Off, Subitems table and Visibility (Content view > Locations tab).

screen shot 2017-04-16 at 8 22 01 am

### CODE REVIEW

**Comment by inakijv** [comment]
Self-note: update sub-items switcher icons to fill mode for better rendering.

**Comment by inakijv** [comment]
Ping @SylvainGuittard

**Comment by SylvainGuittard** [comment]
@inakijv I think sub-items switcher cannot be like that because of the extensibility. We can discuss this topic tomorrow.

**Comment by inakijv** [comment]
Sure! :-) This option also allow us to include a third option :-)

**Comment by inakijv** [comment]
@dpobel What would be the best option for you for the sub-items switcher from the extensibility point of view? What's the current configuration for it? Thanks! :-)

**Comment by inakijv** [comment]
Reviewed and updated ping @SylvainGuittard

**Pull request merged**
