### PR TITLE
Updated colors and buttons based on review

### PR DESCRIPTION
**Pull request by inakijv**
Most important aspects:

- Updated colors labeling based on feedback (rest of colors not included here are component specific;
- Updated buttons based on new classification suggested.

screen shot 2017-05-25 at 11 22 57 am

screen shot 2017-05-24 at 11 14 29 am

### CODE REVIEW

**Comment by inakijv** [comment]
Ping @SylvainGuittard @dpobel

**Comment by SylvainGuittard** [comment]
Did you change the color of `Text hyperlink`?

**Comment by inakijv** [comment]
No, I did not. It might look, but it's not the same. But there is a reason for that. When selecting the color for hyperlink I tested that the possible color combinations (text & background) follow at least one or more of the ratios that the WCAG 2.0 specifies. Most of the colors that pass this test are within blue hues.

**Comment by inakijv** [comment]
Ping @SylvainGuittard

**Pull request merged**
