### PR TITLE
Added a simple front page to make content accessible to robots, etc.

### PR DESCRIPTION
**Pull request by janit**

### CODE REVIEW

**Comment by dpobel** [comment]
with `html`, `head` and `body` elements that would be a tad better :)

**Comment by andrerom** [comment]
Merging as it is better then nothing ;)

@inakijv / @SylvainGuittard We should also add link to UI guidelines.

**Comment by SylvainGuittard** [comment]
Was this frontpage for http://ezsystems.github.io/ ?
If so, it's not working. :(

**Comment by adamwojs** [comment]
It does not work because it was PR with README file changes.

zrzut ekranu 2017-05-24 o 15 59 41

**Comment by andrerom** [comment]
fixed, README is missing now, but the previous one was empty anyway, PR welcome :)

**Pull request merged**
